### PR TITLE
Pkg-config for database options

### PR DESCRIPTION
**Pull request by Mr-DaveDev**
1.  Revise the search for the database options to use the pkg-config files
2.  Revise the mmal to use the --no-as-needed

### CODE REVIEW

**Comment by brianjmurrell** [comment]
```
# pkg-config --exists mysqlclient
# echo $?
1
# rpm -qa | grep maria
mariadb-devel-5.5.52-1.el7.x86_64
mariadb-libs-5.5.52-1.el7.x86_64
mariadb-server-5.5.52-1.el7.x86_64
mariadb-5.5.52-1.el7.x86_64
# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core) 
Release:        7.3.1611
Codename:       Core
```

As you can see, `mariadb-devel` on CentOS does not have pkg-config support.

So while I generally am in support of avoiding hard-coded paths, that won't work for CentOS (or any other RH derived distribution including both EL and Fedora and it's derivitaves).

**Comment by jogu** [comment]
It sounds like there's a risk of regression here? I guess we shouldn't merge this yet.

**Comment by tosiara** [comment]
What if we merge this into a test branch  (together with all recent changes) and ask db users to build and test?

**Comment by jogu** [comment]
@tosiara I'm not sure how that would help? The code relies on pkg-config and Brian's comments here and on his own pull request seem to show that a number of distributions don't have pkg-config support for mysql.

**Comment by brianjmurrell** [comment]
Why not use the various checks in order of priority.  _pkg-config_ first probably and then fall back to known distro locations such as my patch provides for CentOS.  Then as distros move to a _mysql_ release with _pkg-config_ available, the distro-specific fallbacks will just not get used.

**Pull request closed without merging**
