### PR TITLE
Fix track.c with V4L2

### PR DESCRIPTION
**Pull request by slokhorst**
As mentioned in #272

### CODE REVIEW

**Comment by eatdust** [comment]
Hi guys,
I have a logitech QuickCam orbit AF, with tracking and the tracking does not work with motion-4.0.1.
I am happy to perform additional tests if needed.

In fact, the tracking works fine under "guvcview", which only uses uvcvideo driver. If I set this option in motion.conf, track_type=5, I get an error message on the command line:

[1:ml1] [ERR] [TRK] track_center: internal error, 5 is not a known track-type: Invalid argument
Let me know if you want me to open a new bug report for this!

and nothing happens when motion is running.

PS: Thanks for taking back the devel of motion, that is a nice piece of software!

Cheers,
Chris.

**Comment by Mr-Dave** [comment]
Can you build and test the current master and if the issue still persists, open a new issue with a posting on gist of the config and output log.

**Comment by eatdust** [comment]
Thanks, the master indeed finds the camera tracking now. It seems that uvc_center fails to properly reset the camera though, the tilt is ok but the pan goes to its maximum value and remains locked in there.
I am trying to debug and let you know!
cheers.

**Comment by eatdust** [comment]
Managed to fix uvc_center, a SLEEP(1,0) is missing between the PAN and TILT reset, sending two ioctrl without delay seems to confuse the camera. The rest is completely screwed up however, the camera moves in complete random directions and get locked in max PAN, max TILT. I guess all this part should be rewritten from scratch, maybe using UVC_*.
Thanks for the help.

**Pull request merged**
