### PR TITLE
On camera move

### PR DESCRIPTION
**Pull request by christophe-lohr**

### CODE REVIEW

**Comment by christophe-lohr** [comment]
Dears,
  this patch add a new option:  "on_camera_move",  a command to be
executed when the camera has to be moved in tracking mode.
For instance, the command can move the camera according to its API (see example), or something else...

This hook is then called by   track_center()  and   track_move()

Best regards

**Comment by Mr-Dave** [comment]
Thanks for the PR.  There are some issues on this PR and as this is the essentially the first that I've looked at the tracker section, there some other issues to address.

**Comment by christophe-lohr** [comment]
Many thanks for your interest. Could you please tell me more about issues you seen? How may I help?

**Comment by Mr-Dave** [comment]
My initial thoughts are:
1.  We probably do not want to include the `camera5-dist.conf` The project already includes four samples which I think it too many already.  

2.  I think the script ` on_camera_move_netcam-dist.sh` may be better for inclusion in the `motion_config.html` either under the description of the `on_camera_move` section or within the general description section of tracking [here](https://github.com/Motion-Project/motion/blob/82c84fbb27137d67e149ca2adf6b8ab052726292/motion_config.html#L4930).  I have been putting the sample scripts into the guide so that the code base remains (relatively) clean.

3.  The criteria for executing the script in `track_move` and `track_center` is based upon `if (cnt->conf.on_camera_move)`  This could cause conflicts.  Users could specify a script and also specify a different tracking_method.  I think that if we add a new tracking type like `TRACK_TYPE_SCRIPT` it would fit in better.

4.  I did some research on all these variables for tracking and how they are used in Motion.  There is a lot of old stuff in here.  From what I see a lot of them relate either to home built hardware (http://lavrsen.dk/foswiki/bin/view/Motion/MotionTracking) or are for specific cameras and required as parameters into the Motion functions that execute the moving.  I think that the only thing that our script needs to perform the move is the center of the motion and the image dimensions which are available via the current conversion specifiers.  Meaning that we may not even need to set environment variables, we could pass those four items into the script as parameters.

**Comment by christophe-lohr** [comment]
Point 1&2:
You're right, let's keep the code base clean. 
I remove camera5-dist.conf, and I put the on-camera_move_netcam.sh example into motion_config.html

The other points are matter of choice. This is why I need others opinion.

Point3:
In a early attempt I had choose to call the hook only in case of the TRACK_TYPE_GENERIC.
This sounds consistent since the hook could be seen as a generic mean to move a camera.
And this correspond to my own need (managing a PTZ netcam).

I wonder if there could be other use cases where one need to call a third-party command even if one use a PTZ cam type managed by 'motion' itself.

For instance, let's imagine you want to use 'motion' and a stepper camera as a indoor geolocation device for a home-automation system: 
this tracks users in the room and switch on lights on his/her path.
(Well, there are probably better ways to do this, this is just an example.)
In such a case, the hook is not used to move the camera (the stepper mode of 'motion' does it), 
but the hook is used to compute user's position based on provided figures and select lights to switch on in the room.

Do you see what I mean? 
Whell, honestly it's a little bit complicated... I know.
One could forget it and simply settle that 'on_camera_move' is dedicated to a generic mean to move camera and only call it on TRACK_TYPE_GENERIC
What's your opinion?

Point4:
My own need is to move an netcam. My script uses 4 parameters: cent->x cent->y (position of the motion), and imgs->width imgs->height (image size)
In fact, this could even be simplified into only 2 (x,y) parameters: the position of the motion in terms of percent of the image size.
Only two parameters could be provided to the called hook:
  x = 100 * cent->x / imgs->width
  y = 100 * cent->y / imgs->height
This would be enough for my own need to know if the motion to track is on the left/right/up/down, and to sends the corresponding commands to the netcam.

However, in order to keep this as generic as possible, I decided to pass almost all members values of data structures 'struct coord *cent' and 'struct images *imgs'
(except pointers and nested data structures from 'struct images' that sounds me to be for internal use)
For instance 'struct coord *cent' contains many precisions about the detected motion (the size, a bounding box). This could be interesting for some scripts, I gess.
Isn't it?

The remaining point is about passing configuration option 'cnt->track.*' from the 'struct trackoptions' data structure.
These where configured by the user himself in the motion.conf file.
These are not dynamic values computed by algorithms of 'motion'.
These are parameters read from the configuration file and passed as-is to the called hook.
I don't know if there is a hug interest to pass this to the called hook. The called hook may manage its own configuration file by himself if needed.
However I thought that this would be better if all configuration information com from the same place.
Moreover I had questions about a use case: when the camera is hanging on the ceiling, upside down. This may be configured by 'track_motor{xy}_reverse'. 
This could be interesting for the called hook... or not... I don't know.

But finally this is not a big deal to pass plenty of parameters as environment variables.

What's your opinion?

**Comment by Mr-Dave** [comment]
You are right regarding these being matter of opinion.  These are some additional thoughts.
_Do you see what I mean?
Whell, honestly it's a little bit complicated... I know.
One could forget it and simply settle that 'on_camera_move' is dedicated to a generic mean to move camera and only call it on TRACK_TYPE_GENERIC
What's your opinion?_

I do understand there would be scenarios in which it could be useful but it would also complicate the  understanding of how to get it to work.  Most users are not programmers and probably would have a hard time understanding the interactions that could occur.  (They set up a script to move the camera but also specified a type of uvcvideo).  That would really throw things off because one would compound another.  I would favour just putting it as the `TRACK_TYPE_GENERIC` and keeping it as straight forward as possible.  

_The remaining point is about passing configuration option 'cnt->track.*' from the 'struct trackoptions' data structure........_

You are right it isn't a big deal to send the additional ones but the simplicity theme comes to mind.  For this PR, I could actually go either way.  (Either include them or exclude them).

At some time in the future (perhaps years at my current pace), I do anticipate there would only be the two options of uvcvideo and this custom script option.

**Comment by christophe-lohr** [comment]
> I would favour just putting it as the TRACK_TYPE_GENERIC and keeping it as straight forward as possible.

Ok, no problem, I change it.

Note that for now, my 'on_camera_move' option is handelled internally by the 'struct config', side to others 'on_xxxx_events'
So, if one changes the philosophy of this option to be the generic way to move a generic camera, it would be better to handle it into the 'struct trackoptions', isn't it?
I also propose to move explaination from the 'Script Execution' section to the 'Tracking' section of 'motion_config.html'
And it propably be better to rename it in something else such as 'generic_camera_move', to avoid confusion with others 'on_xxxx_events' scripting facilities and clearly settle that this is bound the 'generic' tracking mode.

If you agree, I do the changes and post another PR, ok?

**Comment by Mr-Dave** [comment]
You are correct.  It would be better inside the track if possible and definitely renaming the option.  Also, I think these two points are related.  e.g. To put it in the track config specification, we need to rename the option to begin with "track".   So the option name would need to be something like  `track_generic_move`

**Comment by Mr-Dave** [comment]
closing per PR #643

**Pull request closed without merging**
