### PR TITLE
New feature proposal - Custom text HTTP API

### PR DESCRIPTION
**Pull request by tosiara**
Added custom text HTTP API via new {custom} specifier
To update text send GET request to webcontrol "/0/action/custom/hello%20text"
Add this to config: text_left %{custom}

If there is interest in merging this - I will work on documentation updating

### CODE REVIEW

**Comment by tosiara** [comment]
Addresses https://github.com/Motion-Project/motion/issues/557

**Comment by tosiara** [comment]
If the maintainer accepts this PR, I can then merge it together with https://github.com/Motion-Project/motion/pull/592 and rebase

**Comment by Mr-Dave** [comment]
I do not understand this one.  Why wouldn't this just be accomplished by setting the text_left parameter directly?

**Comment by tosiara** [comment]
In case you want to have more text there, like `System at %{host} load: %{custom}, version: %{ver}, fps: %{fps}`

**Comment by Mr-Dave** [comment]
I am still not following why this would not be set as a direct update to `text_left` / `text_right` with the value filled in via the external script (which presumably is how the load is determined).

**Comment by tosiara** [comment]
If you supply a full string from your script to `text_left` you won't be able to add internal motion's values, like actual frame rate, or any other variable that is only available to motion's process . Having external data as a separate variable is more universal way, for example, you can then use `%{custom}` as a file name too. This example demonstrates my point:
`System at %{host} load: %{custom}, version: %{ver}, fps: %{fps}`
Where `custom` value will come from a script, while all other are internal variables

**Comment by Mr-Dave** [comment]
Users would have to create a script to update / obtain the variable to send to the URL so why wouldn't we just have them update the entire parameter to what they want?  This is an example doing host, load, fps and time (which I'll add to the documentation)

#!/bin/sh  
LOAD=`top -b -n2 | grep "Cpu(s)" | awk '{print $2+$4}' | tail -n1`   
TEXTLEFT=""  
TEXTLEFT=$TEXTLEFT"System%20at%20%25%7Bhost%7D"  
TEXTLEFT=$TEXTLEFT"\nCPU%20$LOAD%20"  
TEXTLEFT=$TEXTLEFT"\nfps:%20%25%7Bfps%7D"  
TEXTLEFT=$TEXTLEFT"\nDate:%20%25Y-%25m-%25d"  
TEXTLEFT=$TEXTLEFT"\n%25T-%25q"  
curl http://localhost:8080/1/config/set?text_left=$TEXTLEFT

**Comment by tosiara** [comment]
Your approach looks a bit heavy to me. And you will have to maintain `text_left` at both config and script in case you would need to change it. But I will probably close this PR as it looks to not add any value to the project. The change has been merged into my fork, so feel free to reopen this PR at any time

**Pull request closed without merging**
