### PR TITLE
autoconf: allow out-of-tree builds.

### PR DESCRIPTION
**Pull request by ipuustin**
Fix `Makefile.in` so that it doesn't require build tree to be the same as the source tree.

### CODE REVIEW

**Comment by ipuustin** [comment]
Added a commit to fix also CMake out-of-tree builds.

**Comment by tosiara** [comment]
Has anyone tried this patch and can also confirm it is working and not breaking anything?

**Comment by ipuustin** [comment]
You can try the out-of-tree build with something like this (autoconf):

    mkdir b && cd b && ../configure && make && make install

With CMake do this:

    mkdir b && cd b && cmake .. && make && make install

**Comment by tosiara** [comment]
Thanks for clearing, this will definitely help in testing

**Comment by tosiara** [comment]
First question: How do I run `autoreconf -fiv` out of tree?
Second: motion compiles this way, but I don't get output of the compilation process (*.o files). It looks just like:
```
$ make
Generating dependencies, please wait...

Welcome to the setup procedure for Motion, the motion detection daemon! If you get
error messages during this procedure, please report them to the mailing list. The
Motion Guide contains all information you should need to get Motion up and running.

Version: 4.0.1+gitcefaa4d
Platform: Linux (if this is incorrect, please read README.FreeBSD)

Compiling Motion object files...
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Motion object files compiled.

Linking Motion...
--------------------------------------------------------------------------------
gcc  -o motion motion.o logger.o conf.o draw.o jpegutils.o video_loopback.o video_v4l2.o video_common.o video_bktr.o netcam.o netcam_ftp.o netcam_jpeg.o netcam_wget.o track.o alg.o event.o picture.o rotate.o webhttpd.o stream.o md5.o netcam_rtsp.o ffmpeg.o  -lm  -pthread -ljpeg   -lavutil-ffmpeg -lavformat-ffmpeg -lavcodec-ffmpeg -lswscale-ffmpeg -lavdevice-ffmpeg
--------------------------------------------------------------------------------
Motion has been linked.

Build complete, run "make install" to install Motion!
```

**Comment by ipuustin** [comment]
First question: `autoreconf`, in a sense, is part of preparing the source tree for building. It should be run in the source directory. Afterwards, you can do as many builds with whatever configure options you like by running `configure` from various build directories.

Second question: I left the `echo` statement here uncommented: https://github.com/Motion-Project/motion/pull/453/files#diff-7e056ddc530791272d363e50c1f25647R105 I thought it was supposed to not print anything... I can change it if you like and update the PR.

**Comment by tosiara** [comment]
Let's make it to be the same as traditional ./configure ad output entire compile process
I thought it hung and killed it few times before it was able to build motion :)

**Comment by ipuustin** [comment]
@tosiara : the compilation output should be fixed now.

**Comment by tosiara** [comment]
CMAKE has been removed. Would you like to rebase your branch to remove changes related to cmake?

**Comment by ipuustin** [comment]
Rebased. Why did you remove cmake support?

**Comment by tosiara** [comment]
See this discussion: https://github.com/Motion-Project/motion/issues/460

**Pull request merged**
