### PR TITLE
Add optimized SSE2 routines for bottleneck functions

### PR DESCRIPTION
**Pull request by aklomp**
This pull request provides SSE2 vectorized implementations of `alg_update_reference_frame()` and `alg_noise_tune()`. Profiling with Callgrind on my Atom server showed that the first was the most expensive single function call. Rewriting it in branchless SSE2 code cuts Motion's load average roughly in half for me. Per-function benchmarking shows a speedup of around 2× for `alg_update_reference_frame()`, and around 4× for `alg_noise_tune()`. Results differ across hardware and compilers, but always show significant speedup.

The plain functions have been lifted out of `alg.c` and placed in the new `alg/` subdirectory, along with their SSE2 versions. In `alg.c`, the preprocessor chooses between including plain or SSE2 functions at compile time. This is perhaps not in line with the rest of the codebase, but made it possible to build a test harness around the functions that checks their correctness and does performance benchmarks. This harness can be found in `alg/tests`.

My website has a [writeup](http://www.alfredklomp.com/programming/sse-motion) of how I converted `alg_update_reference_frame()` to branchless code. It demonstrates how to derive the logic step by step, and is a kind of giant comment on the code. Hopefully it will help in reviewing the code for correctness.

This code took quite some time to write, but probably deserves more real-world testing than it's had so far. All comments welcome!

### CODE REVIEW

**Comment by aklomp** [comment]
Care to comment on why this should be closed?

**Comment by jogu** [comment]
Ah. It wasn't deliberately closed. It seems GitHub automatically closed it because I deleted the (unused since 2015) unstable branch which this pull request is trying to merge into.

I think we should update this one to be merging into master.

**Comment by aklomp** [comment]
I see, that explains it. In fairness, I also haven't done anything to further this issue in the past two years. The patches themselves probably won't even fit on the latest codebase.

Looking back, I'd probably take a different approach to what I tried to do here. Start with building a test framework, insert tests for the functions in question, then carefully add SIMD versions of those functions. As it stands, I can understand the reluctance to merge it.

I'll think about what to do with this patchset, it's been a while since I was involved in Motion development.

**Comment by tosiara** [comment]
Would be nice to implement SSE2/SIMD/NEON (whatever possible) optimizations in the new codebase

**Pull request closed without merging**
