### PR TITLE
Add support for Movidius NC stick

### PR DESCRIPTION
**Pull request by jasaw**
Original issue here: https://github.com/Motion-Project/motion/issues/826

This series of patches add support for Movidius NC (MVNC) stick for more reliable person/cat/dog/car detection. New configuration items are introduced:
- `mvnc_enable <on|off>` : Original motion detection algorithm is used when this is disabled. When enabled, MVNC will be used instead.
- `mvnc_graph_path <path to MobileNetSSD graph>` : This must point to MobileNetSSD graph file. Other neural net models are **not** supported.
- `mvnc_classification <person,cat,dog,car>` : A comma separated classes of objects to detect.
- `mvnc_threshold <0 to 100>` : Inference confidence level for a detection to be considered valid.

Multiple camera streams will either:
- require multiple Movidius NC sticks, one stick per camera stream.
- or enable `mvnc_enable` on one stream only, all other streams use original detection method.

### CODE REVIEW

**Comment by Mr-Dave** [comment]
I have not reviewed it all yet but the first concern would be that we will not be able to accept the binary file. If that file is not included, is there a fall back for users to get it from somewhere else?

**Comment by jasaw** [comment]
On 2nd thought, we could keep the pre-trained MobileNet SSD caffe model, which is another binary file of 22MB. We then compile this caffe model and its prototxt file to give us a graph file.
This caffe model file essentially is your "source" file that is generic enough to run on any machine that supports it.

**Comment by Mr-Dave** [comment]
My concern with the binary is that the project would be dropped from Debian if it were included in the source.  They would rightfully argue that users would have no way of determining whether it was malicious or invading their privacy.  Also, it has a different license which I'm not sure about the compatibility and finally, if it goes on the Motion project site somewhere, in effect we'd own it.  Which would then mean we'd be expected to fix it, compile it, revise it, document it, etc  In effect, it would be its own application.  I have no problem linking / directing users to somewhere but I just don't think pulling in a binary would be good.

**Comment by jasaw** [comment]
OK, I understand now. We could have the Makefile download the caffe model and prototxt then compile to graph, but have it as an optional target that users can trigger, similar to how Intel does it. On top of that, we could add step-by-step instructions to get to a graph file. The risk is we'll be relying on external repo for the caffe model, which we have no control over.

**Comment by jasaw** [comment]
Alright, I have removed the binary file.

**Comment by Mr-Dave** [comment]
I was actually thinking more along the lines of an update to the Motion_guide.html and possibly referring them to your repo/web site to get / build what they need.

**Comment by jasaw** [comment]
Yes, we should definitely update Motion_guide.html and I can keep the caffe, prototxt, and graph files in my repo for anyone who just wants to download and use them.
For those who are building from source, it's still good for them to be able to build their own graph file from the Makefile.

**Comment by Mr-Dave** [comment]
I think we can then remove the pull from git in the configure.

**Comment by jasaw** [comment]
@Mr-Dave Alright, I have removed the graph pull in configure.

**Comment by jasaw** [comment]
I'm closing this PR in favor of a generic motion detection interface.

**Pull request closed without merging**
