### PR TITLE
Add netcam_params

### PR DESCRIPTION
**Pull request by Mr-DaveDev**
- Add `netcam_params` and `netcam_high_params` options.
  - Allow user specification of any additional options to netcams.
- Implement a standard set of routines for parsing parameters provided for both video devices and netcams.
- Revise option names for consistency
  - `vid_control_params` => `video_params`
  - `mmalcam_control_params` => `mmalcam_params`
  - `videodevice` => `video_device`
  - `tunerdevice` => `tuner_device`
  - `netcam_highres` => `netcam_high_url`
- Conversion to use `video_params` for the following:
  - `v4l2_palette` => `video_params` option of `palette`
  - `input` => `video_params` option of `input`
  - `frequency` => `video_params` option of `frequency`
  - `norm` => `video_params` option of `norm` 
- Conversion to use `netcam_params` for the following:
  - `netcam_rate` => `netcam_params` option of `capture_rate`
  - `netcam_decoder` => `netcam_params` option of `decoder`
  - `netcam_use_tcp` => `netcam_params` option of `rtsp_transport` 
  - `netcam_proxy` => `netcam_params` option of `proxy`
  - `netcam_keepalive` => `netcam_params` option of `keepalive`
  - `netcam_tolerant_check` => `netcam_params` option of `tolerant_check`

### CODE REVIEW

**Comment by tosiara** [comment]
To make sure, this only affects code's variables and not config option names?

**Comment by tosiara** [comment]
Ah, I see, it changes also config params: https://github.com/Motion-Project/motion/pull/1226/files#diff-743ad6b4d182586aadb8bd262eaf6fc2d47298e4360f3365a6ee2e0ce8ec494cR334

Then, docs and motion-dist.conf should be also updated

**Comment by tosiara** [comment]
I have upgraded one of my RTSP cameras, and motion stopped working using the same config. Looks like it is looping through the reconnect:
```
[2:nc2:camera1] [NTC] [NET] netcam_rtsp_connect: norm: Camera (camera1) connected
[2:nc2:camera1] [NTC] [NET] netcam_rtsp_connect: norm: Netcam capture FPS is 10.
[2:nc2:camera1] [NTC] [NET] netcam_rtsp_connect: norm: Camera source is 12 FPS
[2:nc2:camera1] [WRN] [NET] netcam_rtsp_connect: norm: Capture FPS rate is less than camera FPS.  Decoding errors will occur.
[2:nc2:camera1] [WRN] [NET] netcam_rtsp_connect: norm:  Better decoding occurs when netcam capture FPS is slightly larger than camera FPS
[2:nc2:camera1] [INF] [NET] netcam_rtsp_interrupt: norm: Camera reading (camera1) timed out
[2:nc2:camera1] [INF] [NET] netcam_rtsp_read_image: norm: Interrupted
[2:nc2:camera1] [INF] [NET] netcam_rtsp_interrupt: norm: Camera reading (camera1) timed out
[2:nc2:camera1] [ERR] [NET] netcam_rtsp_handler_reconnect: norm: Reconnecting with camera....
```
In my case, adding `netcam_rate 12` to the config seems to resolve the issue

But it looks like a bit strange from UX side. I have no idea which "real" rate comes from the camera. The settings are set to 10 fps there. But motion detects 12 and stops working because of a mismatch. Backward compatibility with older config will be now broken and user required to start motion, note the number from the output and put into config manually to resolve the issue.

Wouldn't it be better to automatically update framerate to match netcam_rate if the config does not specify bot of them?

**Comment by Mr-DaveDev** [comment]
Yea, I can change it back to defaulting to camera rate plus a few frames.  We can not update `framerate` because that would just break it for every PI user.   

As for the rate of 12 instead of 10, the 12 is what the ffmpeg libs provided as the average fps provided from the camera.

**Pull request merged**
