### PR TITLE
Added new {host} variable into motion-dist.conf

### PR DESCRIPTION
**Pull request by tosiara**
Added new {host} variable into motion-dist.conf

### CODE REVIEW

**Comment by Mr-Dave** [comment]
This isn't the direction that I'd like to take with the config file.  I'd like the config to just include the basics to get users going and have a reference to the guide where all options, detailed descriptions and various uses is provided.

**Comment by tosiara** [comment]
Include basics - that's what this pull is for. `{host}` is very new thing and if you don't mention it in the motion-dist.conf most experienced users will just miss that

**Comment by Mr-Dave** [comment]
I would view this as advanced and addressing a very special use case where you'd want the host instead of just hard coding it.  I am also thinking that basics would mean that we wouldn't have _any_ of the conversion specifiers listed in the config.  It would just just list the option with a valid value.  The first line of the config would say "Please see the guide <insert local location> for all the available options"

**Comment by tosiara** [comment]
I know that it is easier to maintain a huge guide and send users to read it everytime anyone asks for available param values. But there are many good projects that provide default config files with lots of comments and sample values, like:
http://oss.segetech.com/intra/srv/dnsmasq.conf
https://w1.fi/cgit/hostap/plain/hostapd/hostapd.conf
Why would motion not go the same way? What are the real cons of having config params explanation in `motion-dist.conf`?

**Comment by tosiara** [comment]
Closing as there were no interest in merging. Reopen if needed

**Pull request closed without merging**
