### PR TITLE
Updated extpipe examples with ultrafast H264 (ffmpeg, mencoder and x264)

### PR DESCRIPTION
**Pull request by tosiara**
Guys, what do you think about extending examples of `extpipe`? The existing one may be too scary for users, so I have added few more. They are simple and use different encoders to better demonstrate the approach.
```
Updated extpipe examples with ultrafast H264 (ffmpeg, mencoder and x264)
Also updated previous example to use %w and %h variables
```

### CODE REVIEW

**Comment by jogu** [comment]
Extending examples sounds fine to me. I think we should add a single line comment before each one trying to summarise the pro/con of each option, i.e. help the user understand which one they might want to use and why.

Even in motion_guide.html our explanation of why a user might want to use extpipe or what the example command does is pretty light.

**Comment by tosiara** [comment]
Fine, I will also push a note into guide

**Comment by Mr-Dave** [comment]
I agree that this is better to be part of the motion_guide.html as well as the motion.1 files.  In there we can explain why users would want to use this option, how to use it, examples explaining it, etc.  I do not use the extpipe option at all so adding more of an explanation of this would help.  I would also like to open a discussion issue on whether to move many of the options and most of the documentation out of the config file and simply point to the guide.

**Comment by tosiara** [comment]
Personally, I like the style, when config file has commented examples and description of config params

**Comment by tosiara** [comment]
Are we ok to merge this one?

**Pull request merged**
