### PR TITLE
use current frame timestamp as movie initial PTS reference point

### PR DESCRIPTION
**Pull request by jasaw**
This should hopefully address https://github.com/Motion-Project/motion/issues/1043.

### CODE REVIEW

**Comment by Mr-DaveDev** [comment]
I will have to think about this one.  My first impressions is that this is not going to be the solution.  
The use of the `image_ring_out` is to pick up the first image in the buffer to account for the `pre_capture` situation. i.e. User specifies minimum motion frames of 30 with a pre capture of 30.  
When the `EVENT_FIRSTMOTION` is triggered here, it is at the 30th frame.  We would want the timestamp to reference frame 1 for the movie and not the 30th.

**Comment by jasaw** [comment]
@Mr-DaveDev `ffmpeg_set_pts` function handles the `pre_capture` scenario already.
```
        if (pts_interval < 0){
            /* This can occur when we have pre-capture frames.  Reset start time of video. */
            ffmpeg_reset_movie_start_time(ffmpeg, tv1);
            pts_interval = 0;
        }
```

**Comment by jasaw** [comment]
Hopefully this diagram makes it easier to visualize.
```
Image no.
1                                       <-- ffmpeg->start_time used to be here
2                                           |
3                                           |
...                                         |
28                                          |
29                                          |
30  <--- latest in pre_capture buffer       V
img <--- cnt->current_image             <-- move ffmpeg->start_time here instead
```

When `pre_capture` is non-zero, we end up with negative PTS value, but `ffmpeg_set_pts` function handles that scenario.

**Comment by Mr-DaveDev** [comment]
Do we also have to consider all the other events triggered by `FIRST_MOTION`?  I think it could be possible that they would need the timestamp for example creating directories and this could lead to files with prior times being placed within them...or the database updates?

**Comment by jasaw** [comment]
From reading the code without actually testing it in all scenarios, I think `FIRST_MOTION` events handlers are fine.

The only exception is the `IMAGE_DETECTED` event.
```
            /* Output the picture to jpegs and ffmpeg */
            event(cnt, EVENT_IMAGE_DETECTED,
              &cnt->imgs.image_ring[cnt->imgs.image_ring_out], NULL, NULL,
              &cnt->imgs.image_ring[cnt->imgs.image_ring_out].timestamp_tv);
```
 It will save images with timestamp prior to start of event and similarly write the timestamp into database. Whether this is really a problem or not, I'm not sure.

**Comment by Mr-DaveDev** [comment]
I'm inclined to use a method like what is referenced in the associated issue for the PR.  While having the timestamp of the `FIRSTMOTION` being later than the timestamps of saved images wouldn't make a difference to me personally, I feel someone would report it as a bug later.

**Comment by jasaw** [comment]
I have no problem with your proposed fix. Happy for me to close this PR? I'll let you  implement the fix and I'll test when it's pushed to master.

**Pull request closed without merging**
