### PR TITLE
Disable passthrough on v4l2 via netcam

### PR DESCRIPTION
**Pull request by Mr-DaveDev**

### CODE REVIEW

**Comment by tosiara** [comment]
Hm.. what was the issue behind this change?

**Comment by Mr-Dave** [comment]
I missed something on this.  I disabled all formats instead of just permitting mjpg and h264.  The passthrough needs to be turned off for the typical raw video format from v4l2 devices because it is not permitted in the MP4 passthrough container.

**Comment by tosiara** [comment]
But that was working fine, wasn't it?
I have the following setup running: one V4L device for low res motion detection and another V4L H264 for passthrough recording. Now with this change such a setup will stop working?

**Comment by Mr-Dave** [comment]
PR #1209 pushed yesterday should resolve it.

**Comment by tosiara** [comment]
Ok, I was confused by `Passthrough disabled for v4l2 via netcam` and has just checked - I can still run the setup with two v4l cameras. Although now the config needs to be updated to reflect highres framerate, so I will test that further and report in a separate issue if I find anything interesting

**Pull request merged**
