### PR TITLE
add UVC support

### PR DESCRIPTION
**Pull request by yamori813**
I tested on FreeBSD 10.4R.

### CODE REVIEW

**Comment by tosiara** [comment]
Have you checked Travis errors?
On the most popular Ubuntu 16.04 it fails with:
```
video_uvc.c:56:20: fatal error: libusb.h: No such file or directory
```

**Comment by tosiara** [comment]
Please check Travis log for more errors

**Comment by tosiara** [comment]
I wish I could test your PR, but it looks like there is no libuvc-dev for Ubuntu 16.04

**Comment by Mr-Dave** [comment]
Couple of observations and questions.

1.  Can you confirm that users would need one of the cameras listed in `uvc_device_list`?  
2.  Since I do not have any one of those cameras, is there a command or method to get the required parameters associated with the webcam I do have (Logitech C270)?
3.  I am assuming this is BSD only and is an additional option instead of the `v4l_compat` and `webcamd` module [method](https://motion-project.github.io/motion_build.html#BUILD_FREEBSD) of getting webcam support.  Correct?
4. From a very very brief review, it seems that we may have threading problems.  If two threads of UVC devices are created, I think the variables declared at the top of `video_uvc` would conflict.  I think that they would need to go into the `cnt` context (preferably with a `uvc_` prefix on their names).  Some other ones (such as `finish`) may also conflict with the global variable defined in motion.c called `finish`

Once I know about these, I will dust off my BSD machine and give it a more extensive test/review.

**Comment by yamori813** [comment]
I hove one more FreeBSD issue.

In configure.ac macro occur error by autoconf 2.69 on FreeBSD 10.4R.

AC_CHECK_PROG([PKGCONFIG],[pkg-config],[yes],[no])
AM_CONDITIONAL([FOUND_PKGCONFIG], [test "x$PKGCONFIG" = xyes])
AM_COND_IF([FOUND_PKGCONFIG],,[AC_MSG_ERROR([Required package 'pkg-config' not
 found, please check motion_guide.html and install necessary dependencies.])])

How to modify this no side effect on Linux ?

**Comment by Mr-Dave** [comment]
So, I will let you work this further.  For my test, it locked when using it under Freebsd and when I configured it to run under Ubuntu it seg faulted.  (@tosiara the lib is called libusb-1.0-dev).

**Comment by yamori813** [comment]
Add multi camera support but I have only one UVC camera.

Check by usbconfig command your camera.

% sudo usbconfig
ugen1.2: <Etron Technology, Inc. ELECOM UCAM-MS130> at usbus1, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=ON (100mA)

Then set motion.conf
videodevice /dev/ugen1.2

**Pull request closed without merging**
