### PR TITLE
Update to mystrftime_long to move gethostname out of the loop

### PR DESCRIPTION
**Pull request by tosiara**
Updated mystrftime_long to move gethostname out of the loop
Added version specifier

### CODE REVIEW

**Comment by tosiara** [comment]
Addresses https://github.com/Motion-Project/motion/issues/567

**Comment by Mr-Dave** [comment]
The %{host} does not appear to be functional for my cameras.

**Comment by tosiara** [comment]
I'm using `%{host}` for file names and text output on all my setups, ARM and x86, Ubuntu 14 and 16 - and all them are working fine:
`timelapse_filename %Y%m%d-timelapse-%{host}`
What issue do you have?

**Comment by Mr-Dave** [comment]
The hostname is not carried into the camera threads.  I think the copying of the parameters to each context is occurring before you set hostname and it is therefore only present on context 0.

**Comment by tosiara** [comment]
Yeah, could be. I never use threads so there is always one context on my machines. Should I fix it or did you find this PR not reasonable enough?

**Pull request merged**
