### PR TITLE
The timestamp- and the generic text no longer default to lower left/r…

### PR DESCRIPTION
**Pull request by flok99**
```
The timestamp- and the generic text no longer default to lower left/right, they can now freely be chosen from left/right upper/bottom.

Added an external event interface which lets you add an extra free text to the image.
```

### CODE REVIEW

**Comment by tosiara** [comment]
Would be great to split those changes so it is clear which feature is introduced by what change

**Comment by flok99** [comment]
The second uses changes by the first.

On Tue, Nov 24, 2015 at 3:20 PM, tosiara <notifications@github.com> wrote:

> Would be great to split those changes so it is clear which feature is
> introduced by what change
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mr-Dave/motion/pull/94#issuecomment-159301907>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by tosiara** [comment]
Ahh, ok, sorry, I saw UDP socket and thought that was something different

**Comment by flok99** [comment]
Well, yeah, well, it listens to a udp socket for its input but then it is a
matter of displaying text in one of the four corners.
So it requires that first change as else it would not have the
wrapper-function for drawing and locating the text.

On Tue, Nov 24, 2015 at 3:40 PM, tosiara <notifications@github.com> wrote:

> Ahh, ok, sorry, I saw UDP socket and thought that was something different
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mr-Dave/motion/pull/94#issuecomment-159307782>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by flok99** [comment]
Please don't merge it yet: double height crashes.

On Tue, Nov 24, 2015 at 3:42 PM, Folkert van Heusden <mail@vanheusden.com>
wrote:

> Well, yeah, well, it listens to a udp socket for its input but then it is
> a matter of displaying text in one of the four corners.
> So it requires that first change as else it would not have the
> wrapper-function for drawing and locating the text.
>
> On Tue, Nov 24, 2015 at 3:40 PM, tosiara <notifications@github.com> wrote:
>
>> Ahh, ok, sorry, I saw UDP socket and thought that was something different
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Mr-Dave/motion/pull/94#issuecomment-159307782>.
>>
>
>
>
> --
> www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by flok99** [comment]
Ok it seems to work.

I found that the original draw_text did some funky things. Like suddenly moving a text to the right or so depending on the length of the text.
I introduced a function where you explicitly say "put this text upper-right or bottom-left or center etc".

**Comment by Mr-Dave** [comment]
I see a python file in the pull.  There was a question on the discussion list a few months back about incorporating python.  To "me" it seems like including a new language into the code base is a pretty big deal.  Even if it is on 99% of the platforms, there is the 1% that don't have it and then all of the other associated dependency and packaging issues.  Even getting a additional package to the building process has caused problems (pkgconf).  I haven't reviewed this pull in detail but is using python critical?

**Comment by flok99** [comment]
Hi,

The python-script is just an example. Anything that can send a udp packet
is fine. Netcat would work too.

On Wed, Nov 25, 2015 at 1:07 AM, Mr-Dave <notifications@github.com> wrote:

> I see a python file in the pull. There was a question on the discussion
> list a few months back about incorporating python. To "me" it seems like
> including a new language into the code base is a pretty big deal. Even if
> it is on 99% of the platforms, there is the 1% that don't have it and then
> all of the other associated dependency and packaging issues. Even getting a
> additional package to the building process has caused problems (pkgconf). I
> haven't reviewed this pull in detail but is using python critical?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mr-Dave/motion/pull/94#issuecomment-159444366>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by tosiara** [comment]
Do we really need that UDP mechanism? Isn't it an overkill?
We already have built-in web server for commands - what if "external" text event is submitted to web server instead of UDP socket?

**Comment by flok99** [comment]
It's a low-overhead system. Yes you could do it via the webserver. One
would need to implement a handler for POST-requests. And I think it is a
bit more difficult to issue those requests from the command-line.
My idea was to have something that can be triggered automatically without a
user needing to click around the web-interface.

On Wed, Nov 25, 2015 at 9:11 AM, tosiara <notifications@github.com> wrote:

> Do we really need that UDP mechanism? Isn't it an overkill?
> We already have built-in web server for commands - what if "external" text
> event is submitted to web server instead of UDP socket?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mr-Dave/motion/pull/94#issuecomment-159530093>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by tosiara** [comment]
I (and many other motion usres) already use `curl ` from command line to force snapshots, turn detection on/off and other commands. So this is pretty common and widely used way to interact with motion. `curl` can make both GET and POST requests from command line

**Comment by flok99** [comment]
Right. But handling post-requests is quite a lot of work. You need to
handle the post itself, the different encoding methods, etc. None of that
is currently in motion so it would have to be invented again. I think it
would be better to throw out the current httpd implementation and replace
it with eg libmicrohttpd.

On Wed, Nov 25, 2015 at 9:26 AM, tosiara <notifications@github.com> wrote:

> I (and many other motion usres) already use curl from command line to
> force snapshots, turn detection on/off and other commands. So this is
> pretty common and widely used way to interact with motion. curl can make
> both GET and POST requests from command line
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mr-Dave/motion/pull/94#issuecomment-159532826>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by tosiara** [comment]
I absolutely agree. Built-in web server should be replaced by something more flexible. And, basically, there are some other stuff that can be also replaced by commonly used implementations. But this is scheduled for major release (which can never happen, he he), for the current version we need to be careful not to break existing code.

**Comment by Mr-Dave** [comment]
The 3.4.1 is in the release candidate stage so this change would have to go into a subsequent version.  I have not looked at the libmicrohttpd but that certainly sounds like the correct direction.  If there is a library that is widely available that meets the need, it should be implemented so that the motion code can focus on its core functionality.

**Pull request closed without merging**
