### PR TITLE
Rewrite sockets to be much simpler and properly support IPv6.

### PR DESCRIPTION
**Pull request by slokhorst**
Remove option ipv6_enabled (IPv6 is always enabled)
Add option localhost_ipv4 (the user must choose to listen to IPv4 and IPv6 localhost, only relevant when the localhost option is set to on)

See #97 for more information

### CODE REVIEW

**Comment by Mr-Dave** [comment]
Can you comment on the the new configuration option?  Is this something that we can just determine for the user in the code and then just set it appropriately?  For example, it will listen on IPV4 unless that is actually not available.  Then it would revert over to IPV6.

**Comment by slokhorst** [comment]
@Mr-Dave The new option only is used when `stream_localhost on` or `webcontrol_localhost on`. It determines on which localhost to listen: IPv6/`::1` (when `localhost_ipv4 off`) *or* IPv4/`127.0.0.1` (when `localhost_ipv4 on`).

I have set the default to `on`, meaning it will only listen on IPv4/`127.0.0.1`. This is consistent with the current behaviour where everyone is using IPv4.

I'm quite certain that this is fine for all users. Some people might want to have motion listen on `::1` instead (although I can't really see an use-case for that right now.. maybe in the far future when people start disabling IPv4), and they can do that by setting the option to `off`.

Anyway, saying all that, I agree that it is quite confusing. I'm not sure if there is any better way to handle all of this. Maybe @jogu could weigh in.

**Comment by jogu** [comment]
I don't really fully understand the pro/con's of the IPv6 vs IPv4 localhost; in particular I can't really think why it would matter.

Ideally we'd probably just listen on both, but that makes the code a lot more complex for no obvious gain.

I've had a read through the code and it definitely seems simpler and more correct to me, and fixes at least one bug so that's good :-)

**Comment by slokhorst** [comment]
The best would probably be to listen on both, but the problem is (I think), you can only specify a single address (or "any" address) for a socket to listen on. So listening on both would require 2 separate sockets, which would require modifications throughout the entire code.

An alternative would be something like [this](http://stackoverflow.com/a/2277559) (also see the question: it's the same problem we're having).

**Comment by Mr-Dave** [comment]
OK.  I don't want to complicate the code with creating two sockets to listen on especially considering we can't come up with a use-case where this would be needed.  And if we can't come to a alternative method that eliminates the configuration option, I'd still like to consider whether we can at least keep the same name.  The <code>ipv6_enabled</code> seems like it would suffice. The description would just be that it is enabling IPV6 when the localhost is restricted to On.  IPV6 is always functional when the localhost is set to off.

**Comment by slokhorst** [comment]
Ok, renamed the option back.

**Pull request merged**
