### PR TITLE
Allow text scaling via compile time scale factor in motion.h

### PR DESCRIPTION
**Pull request by tosiara**
Creating this pull for review

### CODE REVIEW

**Comment by tosiara** [comment]
The feature seems to be useful for users with higher resolutions. Changes does not look intrusive.
Maybe someone can review if the technical implementation is good enough and is correctly covered in documentation

**Comment by colinl** [comment]
Please note that this change was proposed in #395 as a feasibility test to determine how complex an implementation would be, not as a final solution. Whilst I believe the code is solid it definitely comes under the category of hack rather than carefully crafted code. The final solution should include configuration options to allow the scaling to be selected at run time (possibly as described in #395).

**Comment by tosiara** [comment]
You can still push to the same branch and github will automatically add new commit here. So if you plan to invest some time to make this less hack, but more a configuration feature - you are welcome and we really appreciate your efforts!

**Comment by colinl** [comment]
If it is considered useful (which it seems it is) then I will attempt to complete the task, though at this precise moment I am a bit busy so it may be a little while.
Is my proposal for configuration ok? So a new configuration item text_scale which would be set to the scaling required (integer 2, 3, 4 etc). To provide backwards compatibility, if this is not set, then text_double would continue to work as currently. If text_scale is set then text_double would be ignored.

**Comment by tosiara** [comment]
I'm fine with your proposal. The text needs to be scaled. So it is either scale factor, or fixed font size - I really don't care. Both are easy to undertsand and use. So whatever is easier for you to implement

**Comment by Mr-Dave** [comment]
Instead of having this as a compile option, I would like to see about revising our existing parameter of <code>text_double yes/no</code> changed into <code>text_scale 1-10</code> (or some similar range).  This would allow for greater flexibility for multiple cameras situations and resolutions.

**Comment by colinl** [comment]
That is exactly my plan (config option text_scale 1-10 or similar). When I will have time to complete it though I do not know. It may have to wait for the long dark evenings to arrive.

**Comment by tosiara** [comment]
After working with different resolutions now I agree with MrDave, we need a config param that specifies text size. Closing this PR

**Pull request closed without merging**
