### PR TITLE
Neon optimizations

### PR DESCRIPTION
**Pull request by notorca**
alg_locate_center_size, alg_diff_standard, vid_uyvyto420p, vid_yuv422to420p are implemented in neon intrinsics. Speedup is 2x-10x depends on architecture. Tested on both, armv7 and arm64.

### CODE REVIEW

**Comment by jasaw** [comment]
I can test this on Raspberry Pi. What do I need to do to enable this feature? Is there a configure option?

**Comment by notorca** [comment]
This changes will work only starting form Raspberry Pi 2, Raspberry Pi does not have NEON. Neon-optimized code enabled if compiler provides __ARM_NEON. It is always enabled for arm64 (Raspberry Pi 3), for armv7 compiler options should contain -march=armv7-a -mfpu=neon-vfpv4.
To build and run test use:
```
gcc -std=gnu99 -g -O3 -march=native -mtune=native -mfloat-abi=hard -mfpu=neon-vfpv4 alg.c alg_neon_test.c -o test_neon
./test_neon
```

**Comment by tosiara** [comment]
Great! I will test it on my bunch of ARM boards. What performance boost should I expect? Do you have any reference numbers?

**Comment by notorca** [comment]
@tosiara Performance improvement is depends on CPU type. For Cortex A7 functions are 2x-5x faster on random data, on real data it could be even more. On A15 and A53 it's up to 10x. 

You can build test executable and run it on your boards, it would be interesting to look at results. The most portable command to do it is
```
gcc -O3 -march=native -mtune=native -mfloat-abi=hard -mfpu=neon alg.c alg_neon_test.c -o test_neon
```
Result should be like this (Cortex-A7 1GHz Cubiboard2):
```
Test test_locate_center_size passed, 30730 vs 14676 (16054) 47.757891%
Test test_locate_center_size passed, 54877 vs 6233 (48644) 11.358128%
Test test_locate_center_size passed, 30513 vs 11347 (19166) 37.187428%
Test test_locate_center_size passed, 38086 vs 7568 (30518) 19.870819%
Test test_alg_diff_standart_one_case:1 passed, 24424 vs 7678 (16746) 31.436292%
Test test_alg_diff_standart_one_case:2 passed, 37701 vs 12678 (25023) 33.627755%
Test test_alg_diff_standart_one_case:3 passed, 40916 vs 20522 (20394) 50.156418%
Test test_alg_diff_standart_one_case:4 passed, 27298 vs 12779 (14519) 46.812953%
Test test_alg_diff_standart_one_case:5 passed, 42668 vs 16878 (25790) 39.556576%
Test test_alg_diff_standart_one_case:6 passed, 49368 vs 26668 (22700) 54.018798%
Test test_alg_diff_standart_one_case:1 passed, 23044 vs 7253 (15791) 31.474570%
Test test_alg_diff_standart_one_case:2 passed, 37786 vs 23251 (14535) 61.533372%
Test test_alg_diff_standart_one_case:3 passed, 48954 vs 25560 (23394) 52.212281%
Test test_alg_diff_standart_one_case:4 passed, 33377 vs 15741 (17636) 47.161219%
Test test_alg_diff_standart_one_case:5 passed, 50269 vs 17910 (32359) 35.628320%
Test test_alg_diff_standart_one_case:6 passed, 50791 vs 27620 (23171) 54.379713%
```
Fist number is time in microseconds of for unoptimized C function, second is for neon, (this is difference), and second/first * 100%.
Different cases cover different branches in function flow.

**Comment by tosiara** [comment]
OrangePi Zero:
```
motion@orangepizero:~/git/motion-tosiara$ gcc -O3 -march=native -mtune=native -mfloat-abi=hard -mfpu=neon alg.c alg_neon_test.c -o test_neon
motion@orangepizero:~/git/motion-tosiara$ ./test_neon 
Test test_locate_center_size passed, 26817 vs 8607 (18210) 32.095313%
Test test_locate_center_size passed, 25035 vs 4119 (20916) 16.452966%
Test test_locate_center_size passed, 26768 vs 8479 (18289) 31.675882%
Test test_locate_center_size passed, 24867 vs 4105 (20762) 16.507822%
Test test_alg_diff_standart_one_case:1 passed, 16011 vs 6387 (9624) 39.891325%
Test test_alg_diff_standart_one_case:2 passed, 31699 vs 11508 (20191) 36.303984%
Test test_alg_diff_standart_one_case:3 passed, 38811 vs 21977 (16834) 56.625699%
Test test_alg_diff_standart_one_case:4 passed, 27409 vs 12493 (14916) 45.579919%
Test test_alg_diff_standart_one_case:5 passed, 38360 vs 17413 (20947) 45.393639%
Test test_alg_diff_standart_one_case:6 passed, 46705 vs 27303 (19402) 58.458409%
Test test_alg_diff_standart_one_case:1 passed, 15421 vs 6451 (8970) 41.832566%
Test test_alg_diff_standart_one_case:2 passed, 31206 vs 11418 (19788) 36.589117%
Test test_alg_diff_standart_one_case:3 passed, 38223 vs 22153 (16070) 57.957251%
Test test_alg_diff_standart_one_case:4 passed, 27079 vs 12383 (14696) 45.729163%
Test test_alg_diff_standart_one_case:5 passed, 38335 vs 17273 (21062) 45.058041%
Test test_alg_diff_standart_one_case:6 passed, 46534 vs 27352 (19182) 58.778528%
motion@orangepizero:~/git/motion-tosiara$ uname -a
Linux orangepizero 3.4.113-sun8i #16 SMP PREEMPT Tue Jun 13 14:15:57 CEST 2017 armv7l armv7l armv7l GNU/Linux
motion@orangepizero:~/git/motion-tosiara$ cat /proc/cpuinfo 
Processor	: ARMv7 Processor rev 5 (v7l)
processor	: 0
BogoMIPS	: 2400.00

processor	: 1
BogoMIPS	: 2400.00

processor	: 2
BogoMIPS	: 2400.00

processor	: 3
BogoMIPS	: 2400.00

Features	: swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

Hardware	: sun8i
Revision	: 0000
Serial		: 94005035c6205c350a4e
```
Running 720 p YUYV @10fps idle motion detection CPU drops from 45% to 36%
Running 720p MJPEG @10fps has no effect on CPU - always 83%

**Comment by tosiara** [comment]
MK808 with dual core RK3066:
```
root@mk808b:/home/ubuntu/motion# gcc -std=gnu99 -O3 -march=native -mtune=native -mfloat-abi=hard -mfpu=neon alg.c alg_neon_test.c -o test_neon
root@mk808b:/home/ubuntu/motion# ./test_neon 
Test test_locate_center_size passed, 23338 vs 6125 (17213) 26.244751%
Test test_locate_center_size passed, 17499 vs 2254 (15245) 12.880736%
Test test_locate_center_size passed, 23260 vs 6155 (17105) 26.461737%
Test test_locate_center_size passed, 16787 vs 2116 (14671) 12.604992%
Test test_alg_diff_standart_one_case:1 passed, 8724 vs 2250 (6474) 25.790922%
Test test_alg_diff_standart_one_case:2 passed, 18468 vs 3296 (15172) 17.847087%
Test test_alg_diff_standart_one_case:3 passed, 20382 vs 7987 (12395) 39.186537%
Test test_alg_diff_standart_one_case:4 passed, 16748 vs 3895 (12853) 23.256508%
Test test_alg_diff_standart_one_case:5 passed, 22486 vs 4786 (17700) 21.284355%
Test test_alg_diff_standart_one_case:6 passed, 24479 vs 8873 (15606) 36.247396%
Test test_alg_diff_standart_one_case:1 passed, 8799 vs 2233 (6566) 25.377884%
Test test_alg_diff_standart_one_case:2 passed, 18510 vs 3315 (15195) 17.909238%
Test test_alg_diff_standart_one_case:3 passed, 20376 vs 8010 (12366) 39.310954%
Test test_alg_diff_standart_one_case:4 passed, 16736 vs 3884 (12852) 23.207457%
Test test_alg_diff_standart_one_case:5 passed, 22463 vs 4775 (17688) 21.257178%
Test test_alg_diff_standart_one_case:6 passed, 24333 vs 8853 (15480) 36.382690%
root@mk808b:/home/ubuntu/motion# uname -a
Linux mk808b 3.0.8+ #26 SMP PREEMPT Mon Mar 18 11:30:34 MSK 2013 armv7l armv7l armv7l GNU/Linux
root@mk808b:/home/ubuntu/motion# cat /proc/cpu
cpu/     cpuinfo  
root@mk808b:/home/ubuntu/motion# cat /proc/cpuinfo 
Processor	: ARMv7 Processor rev 0 (v7l)
processor	: 0
BogoMIPS	: 1631.46

processor	: 1
BogoMIPS	: 1631.46

Features	: swp half thumb fastmult vfp edsp neon vfpv3 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x3
CPU part	: 0xc09
CPU revision	: 0

Hardware	: RK30board
Revision	: 0000
Serial		: 0000000000000000
```
Running 480p YUYV @10fps idle motion detection CPU drops from 8% to 6%

**Comment by tosiara** [comment]
ODROID U3:
```
./test_neon 
Test test_locate_center_size passed, 20517 vs 4562 (15955) 22.235220%
Test test_locate_center_size passed, 15853 vs 1813 (14040) 11.436321%
Test test_locate_center_size passed, 20409 vs 4659 (15750) 22.828164%
Test test_locate_center_size passed, 15765 vs 1818 (13947) 11.531874%
Test test_alg_diff_standart_one_case:1 passed, 7280 vs 1996 (5284) 27.417582%
Test test_alg_diff_standart_one_case:2 passed, 18491 vs 3095 (15396) 16.737872%
Test test_alg_diff_standart_one_case:3 passed, 19494 vs 6192 (13302) 31.763620%
Test test_alg_diff_standart_one_case:4 passed, 14805 vs 3499 (11306) 23.633907%
Test test_alg_diff_standart_one_case:5 passed, 22852 vs 4600 (18252) 20.129529%
Test test_alg_diff_standart_one_case:6 passed, 24091 vs 7133 (16958) 29.608568%
Test test_alg_diff_standart_one_case:1 passed, 7235 vs 1931 (5304) 26.689703%
Test test_alg_diff_standart_one_case:2 passed, 17787 vs 3140 (14647) 17.653342%
Test test_alg_diff_standart_one_case:3 passed, 19538 vs 6101 (13437) 31.226328%
Test test_alg_diff_standart_one_case:4 passed, 15089 vs 3511 (11578) 23.268606%
Test test_alg_diff_standart_one_case:5 passed, 22462 vs 4485 (17977) 19.967055%
Test test_alg_diff_standart_one_case:6 passed, 24062 vs 7418 (16644) 30.828693%
motion@odroid:~/git/motion_project$ uname -a
Linux odroid 3.8.13.30 #1 SMP PREEMPT Mon Sep 19 23:41:49 BRT 2016 armv7l armv7l armv7l GNU/Linux
motion@odroid:~/git/motion_project$ cat /proc/cpuinfo 
processor	: 0
model name	: ARMv7 Processor rev 0 (v7l)
BogoMIPS	: 3394.86
Features	: swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x3
CPU part	: 0xc09
CPU revision	: 0

processor	: 1
model name	: ARMv7 Processor rev 0 (v7l)
BogoMIPS	: 3394.86
Features	: swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x3
CPU part	: 0xc09
CPU revision	: 0

processor	: 2
model name	: ARMv7 Processor rev 0 (v7l)
BogoMIPS	: 3394.86
Features	: swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x3
CPU part	: 0xc09
CPU revision	: 0

processor	: 3
model name	: ARMv7 Processor rev 0 (v7l)
BogoMIPS	: 3394.86
Features	: swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x3
CPU part	: 0xc09
CPU revision	: 0

Hardware	: ODROID-U2/U3
Revision	: 0000
Serial		: 0000000000000000
```

**Comment by tosiara** [comment]
ODROID C1+:
```
./test_neon 
Test test_locate_center_size passed, 23856 vs 10294 (13562) 43.150570%
Test test_locate_center_size passed, 21366 vs 3781 (17585) 17.696340%
Test test_locate_center_size passed, 23759 vs 10124 (13635) 42.611221%
Test test_locate_center_size passed, 21258 vs 3907 (17351) 18.378963%
Test test_alg_diff_standart_one_case:1 passed, 12176 vs 3122 (9054) 25.640604%
Test test_alg_diff_standart_one_case:2 passed, 19759 vs 5716 (14043) 28.928590%
Test test_alg_diff_standart_one_case:3 passed, 23419 vs 9841 (13578) 42.021436%
Test test_alg_diff_standart_one_case:4 passed, 17852 vs 6348 (11504) 35.559041%
Test test_alg_diff_standart_one_case:5 passed, 22031 vs 8974 (13057) 40.733512%
Test test_alg_diff_standart_one_case:6 passed, 25300 vs 12481 (12819) 49.332016%
Test test_alg_diff_standart_one_case:1 passed, 12158 vs 3120 (9038) 25.662115%
Test test_alg_diff_standart_one_case:2 passed, 19734 vs 5768 (13966) 29.228742%
Test test_alg_diff_standart_one_case:3 passed, 23428 vs 9823 (13605) 41.928462%
Test test_alg_diff_standart_one_case:4 passed, 17821 vs 6238 (11583) 35.003647%
Test test_alg_diff_standart_one_case:5 passed, 22087 vs 9084 (13003) 41.128265%
Test test_alg_diff_standart_one_case:6 passed, 25388 vs 12821 (12567) 50.500236%
motion@odroid:~/git/motion_project$ uname -a
Linux odroid 3.10.104-184 #1 SMP PREEMPT Mon Feb 20 06:38:17 UTC 2017 armv7l armv7l armv7l GNU/Linux
motion@odroid:~/git/motion_project$ cat /proc/cpuinfo 
Processor	: ARMv7 Processor rev 1 (v7l)
processor	: 0
BogoMIPS	: 3.27

processor	: 1
BogoMIPS	: 3.27

processor	: 2
BogoMIPS	: 3.27

processor	: 3
BogoMIPS	: 3.27

Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc05
CPU revision	: 1

Hardware	: ODROIDC
Revision	: 000a
Serial		: 1b00000000000000
```

**Comment by tosiara** [comment]
@notorca I have a question. Would it be possible also to implement SSE- and NEON- optimized yuv scale down? This is the function: https://github.com/Motion-Project/motion/pull/454/files#diff-6f4fecf85d9c6ffa7c7e41b89bd26ac5R1233

**Comment by Mr-Dave** [comment]
Before going down the path of coding more cpu specific items, there needs to be a discussion on whether this is an appropriate path for the project.  While the code in this PR provides a performance improvement for a small subset of users, it isn't something that would be used for the vast majority of the users nor is it something that could be maintained.

**Comment by notorca** [comment]
@tosiara I'll add implementation for scaled yuv conversion.

**Comment by notorca** [comment]
alg_update_reference_frame neon implementation added. Next step is to adopt this optimizations for SSE

**Comment by notorca** [comment]
@tosiara can you please test the latest version? I've finished optimization of slowest erode and dilate functions, now cpu usage should be noticeable lower.

**Comment by tosiara** [comment]
Sure, I will check it soon

**Comment by tosiara** [comment]
Alwinner H3 OrangePi Lite
```
motion@orpilite:~/git/motion$ gcc -std=gnu99 -O3 -march=native -mtune=native -mfloat-abi=hard -mfpu=neon alg.c alg_neon_test.c -o test_neon
motion@orpilite:~/git/motion$ ./test_neon
Test test_locate_center_size passed, 26616 vs 9086 (17530) 34.137361%
Test test_locate_center_size passed, 25317 vs 4263 (21054) 16.838488%
Test test_locate_center_size passed, 26315 vs 9518 (16797) 36.169485%
Test test_locate_center_size passed, 25161 vs 4374 (20787) 17.384047%
Test test_alg_diff_standart_one_case:1 passed, 13035 vs 5070 (7965) 38.895282%
Test test_alg_diff_standart_one_case:2 passed, 29798 vs 9586 (20212) 32.169944%
Test test_alg_diff_standart_one_case:3 passed, 34368 vs 17040 (17328) 49.581006%
Test test_alg_diff_standart_one_case:4 passed, 24442 vs 10475 (13967) 42.856558%
Test test_alg_diff_standart_one_case:5 passed, 34975 vs 14630 (20345) 41.829878%
Test test_alg_diff_standart_one_case:6 passed, 40829 vs 21924 (18905) 53.697127%
Test test_alg_diff_standart_one_case:1 passed, 13072 vs 5076 (7996) 38.831089%
Test test_alg_diff_standart_one_case:2 passed, 29074 vs 9142 (19932) 31.443902%
Test test_alg_diff_standart_one_case:3 passed, 34398 vs 17354 (17044) 50.450608%
Test test_alg_diff_standart_one_case:4 passed, 25244 vs 10072 (15172) 39.898590%
Test test_alg_diff_standart_one_case:5 passed, 34932 vs 14892 (20040) 42.631398%
Test test_alg_diff_standart_one_case:6 passed, 41250 vs 21614 (19636) 52.397576%
Test test_alg_update_reference_frame_one_case:1 passed, 29018 vs 20380 (8638) 70.232270%
Test test_alg_update_reference_frame_one_case:2 passed, 2382 vs 2525 (-143) 106.003359%
Test test_alg_update_reference_frame_one_case:3 passed, 14312 vs 8805 (5507) 61.521800%
Test test_alg_update_reference_frame_one_case:1 passed, 28964 vs 20596 (8368) 71.108963%
Test test_alg_update_reference_frame_one_case:2 passed, 2421 vs 2486 (-65) 102.684841%
Test test_alg_update_reference_frame_one_case:3 passed, 14336 vs 8779 (5557) 61.237444%
Test test_erode5 passed, 125792 vs 82473 (43319) 65.562993%
Test test_erode5 passed, 125691 vs 81362 (44329) 64.731763%
Test test_dilate5 passed, 253525 vs 87835 (165690) 34.645498%
Test test_dilate5 passed, 253163 vs 85167 (167996) 33.641172%
Test test_erode9 passed, 175945 vs 85662 (90283) 48.686806%
Test test_erode9 passed, 175550 vs 85783 (89767) 48.865281%
Test test_dilate9 passed, 280762 vs 94157 (186605) 33.536234%
Test test_dilate9 passed, 279992 vs 93220 (186772) 33.293808%
Test test_locate_center_size passed, 26562 vs 9071 (17491) 34.150290%
Test test_locate_center_size passed, 25212 vs 4317 (20895) 17.122799%
Test test_locate_center_size passed, 26398 vs 9779 (16619) 37.044473%
Test test_locate_center_size passed, 25081 vs 4442 (20639) 17.710618%
Test test_alg_diff_standart_one_case:1 passed, 13439 vs 5081 (8358) 37.807873%
Test test_alg_diff_standart_one_case:2 passed, 32871 vs 9142 (23729) 27.811749%
Test test_alg_diff_standart_one_case:3 passed, 37726 vs 17489 (20237) 46.357949%
Test test_alg_diff_standart_one_case:4 passed, 25990 vs 10053 (15937) 38.680262%
Test test_alg_diff_standart_one_case:5 passed, 41564 vs 14156 (27408) 34.058320%
Test test_alg_diff_standart_one_case:6 passed, 47258 vs 21467 (25791) 45.425113%
Test test_alg_diff_standart_one_case:1 passed, 13297 vs 5068 (8229) 38.113860%
Test test_alg_diff_standart_one_case:2 passed, 31216 vs 9103 (22113) 29.161328%
Test test_alg_diff_standart_one_case:3 passed, 36503 vs 16959 (19544) 46.459195%
Test test_alg_diff_standart_one_case:4 passed, 24069 vs 10068 (14001) 41.829739%
Test test_alg_diff_standart_one_case:5 passed, 42125 vs 14531 (27594) 34.494955%
Test test_alg_diff_standart_one_case:6 passed, 46380 vs 22216 (24164) 47.899957%
Test test_alg_update_reference_frame_one_case:1 passed, 28648 vs 20392 (8256) 71.181234%
Test test_alg_update_reference_frame_one_case:2 passed, 2434 vs 2457 (-23) 100.944947%
Test test_alg_update_reference_frame_one_case:3 passed, 14706 vs 8667 (6039) 58.935129%
Test test_alg_update_reference_frame_one_case:1 passed, 28644 vs 19767 (8877) 69.009217%
Test test_alg_update_reference_frame_one_case:2 passed, 2373 vs 2411 (-38) 101.601349%
Test test_alg_update_reference_frame_one_case:3 passed, 14548 vs 8779 (5769) 60.345065%
Test test_erode5 passed, 125632 vs 85689 (39943) 68.206349%
Test test_erode5 passed, 125564 vs 82447 (43117) 65.661336%
Test test_dilate5 passed, 253614 vs 86354 (167260) 34.049382%
Test test_dilate5 passed, 252976 vs 86877 (166099) 34.341993%
Test test_erode9 passed, 175866 vs 87338 (88528) 49.661674%
Test test_erode9 passed, 175683 vs 86215 (89468) 49.074185%
Test test_dilate9 passed, 280741 vs 95385 (185356) 33.976156%
Test test_dilate9 passed, 280077 vs 93829 (186248) 33.501144%
```

**Comment by notorca** [comment]
Closing in favor of https://github.com/Motion-Project/motion/pull/498

**Pull request closed without merging**
