### PR TITLE
Version 4.0.3

### PR DESCRIPTION
**Pull request by tosiara**
Milestone 4.0.3 with improvement, fixes and some new features

### CODE REVIEW

**Comment by jogu** [comment]
We usually build binary packages when we release a new version. Are you doing to do that or are we going to release a new version without binary packages?

**Comment by tosiara** [comment]
My initial idea was to just freeze current tree and name it 4.0.3 while still working on future release, which probably should be 4.1
If there is an easy way to build binaries of 4.0.3 - that would be fine. But I never done that before. Do we have that process documented somewhere?
Looking at https://github.com/Motion-Project/motion/releases there are just debian packages and source zip

**Comment by jogu** [comment]
Yes, sorry, I meant '.deb's when I said binaries.

I'm not sure how well the process is documented. I've never done it, and definitely don't have time to look right now. There is something in this git repo:

https://github.com/Motion-Project/motion-packaging

**Comment by tosiara** [comment]
Oh, I missed that. Will take a look and try to build debs.
If I succeed building it - are we ok to release it as 4.0.3? Any other versioning preferences?

**Comment by jogu** [comment]
4.0.3 is fine by me.

**Comment by Mr-DaveDev** [comment]
I'll be back in a couple of weeks.  I would like the _last_ item on the list to be changing the version number and freezing rather than having it as the first item.  As soon as the version number changes that indicates to distributors of packages (Debian, etc) that everything is pristine and perfect and done.  The project issue log also has a closed item the basic checklist of items when 4.0 was released.

**Comment by tosiara** [comment]
@Mr-DaveDev when would you plan the nearest "official" release?
What would be the cons of making a snapshot (or internal release) of current master as 4.0.3?

**Comment by Mr-DaveDev** [comment]
See comments on #204 .  We'll change the version number when the testing is complete and avoid that situation from reoccurring again.

**Comment by tosiara** [comment]
Assume rejected then

**Pull request closed without merging**
