### PR TITLE
Add HTTP endpoints with camera status information

### PR DESCRIPTION
**Pull request by hansmi**
This change introduces new HTTP endpoints in the stream web server returning
status information regarding a particular or all cameras as a JSON object.
These are useful in implementing system monitoring, e.g. via Nagios or Icinga.

`{IP}:{port0}/cameras.json`: JSON object with IDs and names of all cameras,
e.g.:

```
$ curl -s http://127.0.0.1:8081/cameras.json | jq -rMC .
{
  "cameras": [
    {
      "id": 1,
      "name": "Lobby"
    },
    {
      "id": 3,
      "name": "Lobby"
    }
  ]
}
```

`{IP}:{port0}/{camid}/status.json`: JSON object with information about a single
camera, e.g.:

```
$ curl -s http://127.0.0.1:8081/3/status.json | jq -rMC .
{
  "id": 3,
  "name": "Lobby",
  "image_width": 640,
  "image_height": 480,
  "fps": 15,
  "missing_frame_counter": 1561,
  "running": 1,
  "lost_connection": 1,
  "currenttime": 1573400729,
  "currenttime_iso8601": "2019-11-10T15:45:29+0000",
  "lasttime": 0,
  "lasttime_iso8601": null,
  "lasttime_elapsed": null,
  "eventtime": 0,
  "eventtime_iso8601": null,
  "eventtime_elapsed": null,
  "connectionlosttime": 1573400614,
  "connectionlosttime_iso8601": "2019-11-10T15:43:34+0000",
  "connectionlosttime_elapsed": 115
}
```

Additional endpoints:

- `{IP}:{port0}/status.json`: JSON object with information about all cameras
- `{IP}:{portX}/status.json`: JSON object with information about the camera
  running on port {portX}

Relates to issue #1055.

### CODE REVIEW

**Comment by hansmi** [comment]
@Mr-Dave, could you please review this code?

**Comment by Mr-Dave** [comment]
I've been working on my own branch so I haven't been too much review/revisions on this.  For this PR, I needed to cross reference and view entire files (changed and source) so using the github code review sections wasn't working.  Hopefully you can track the sections I refer to in the following observations.  

It looks like there are some issues on the [automated builds](https://travis-ci.org/Motion-Project/motion/builds/609980058).  PRs were not getting updated with Travis results when this PR was submitted but this should be fixed now.  You can add the `--with-developer-flags` to get specific warnings on your distro but there will possibly be some that are platform specific reflected in the Travis tests.

The additions starting at [line 1163 through 1174](https://github.com/Motion-Project/motion/blob/3c6d194d750cbeed471da56f713cdc3174f1358a/src/webu.c#L1163) are applying the logic to look for the connection type but this is for responses coming on the stream port rather than the control port.  I believe that status requests such as these should be upon the control port.

I do not recall the specific compiler (perhaps FreeBSD) but on `case` statements that fall through, there must be a specific comment to avoid compiler warnings.  A sample can be seen [here](https://github.com/Motion-Project/motion/blob/23dffb03cb7792c5275b707e92aec3294433047c/src/video_v4l2.c#L1064)

I would not expect that it would be required to add a condition on the cmd1 or cmd2 in this [section](https://github.com/Motion-Project/motion/blob/3c6d194d750cbeed471da56f713cdc3174f1358a/src/webu.c#L1209) See above comment on applicability to having this on the stream port.

The [passflag condition](https://github.com/Motion-Project/motion/blob/3c6d194d750cbeed471da56f713cdc3174f1358a/src/webu.c#L1375) needs to remain at the very top to stop early connections.  Otherwise some applications that use Motion as the back-end will not function since they attempt to connect before an image from the first pass is available.  

This isn't wrong but I would comment that I'm more inclined for clarity on lines such as [this](https://github.com/Motion-Project/motion/blob/3c6d194d750cbeed471da56f713cdc3174f1358a/src/webu_status.c#L24) rather than packing multiple initializations and assignments onto one line

I am not sure that [this condition](https://github.com/Motion-Project/motion/blob/3c6d194d750cbeed471da56f713cdc3174f1358a/src/webu_status.c#L91) would work when there is not any camera threads and instead there is just the single motion.conf file.

I had been trying to avoid macros such as [this](https://github.com/Motion-Project/motion/blob/3c6d194d750cbeed471da56f713cdc3174f1358a/src/webu_status.c#L152)  I would think that a function could be used instead and then just passing in the applicable args.

**Comment by hansmi** [comment]
@Mr-Dave, thanks for the review!

> It looks like there are some issues on the [automated builds](https://travis-ci.org/Motion-Project/motion/builds/609980058). […] You can add the `--with-developer-flags` to get specific warnings on your distro but there will possibly be some that are platform specific reflected in the Travis tests.

I had been using `--with-developer-flags`, but you're right that the development platform I'm suing has an influence. I didn't include `inttypes.h` and thus `PRId64` wasn't defined.

> The additions starting at [line 1163 through 1174](https://github.com/Motion-Project/motion/blob/3c6d194d750cbeed471da56f713cdc3174f1358a/src/webu.c#L1163) are applying the logic to look for the connection type but this is for responses coming on the stream port rather than the control port. I believe that status requests such as these should be upon the control port.

I respectfully disagree. The control port is for "write" operations and should be locked down. As of this writing motion only supports a single username/password combination without gradual permissions. Monitoring shouldn't have write access. The implemented requests are read operations with metadata which provide little additional information beyond what's available via the video streams.

> I do not recall the specific compiler (perhaps FreeBSD) but on `case` statements that fall through, there must be a specific comment to avoid compiler warnings.

I wasn't aware of such warnings and researched a bit. [-Wimplicit-fallthrough has been implemented in GCC 7](https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/). It's not in the scope of my change, but you could probably add `-Wimplicit-fallthrough=3` to the developer flags. Please note that in my tests a warning was only raised when there was at least one statement in the case falling through (i.e. not for `case '\\': case '"': …`).

> I would not expect that it would be required to add a condition on the cmd1 or cmd2 in this [section](https://github.com/Motion-Project/motion/blob/3c6d194d750cbeed471da56f713cdc3174f1358a/src/webu.c#L1209) […]

The additional conditions are to avoid requests like `/1/status.json/foo` from being equivalent to `/1/status.json`.

> The [passflag condition](https://github.com/Motion-Project/motion/blob/3c6d194d750cbeed471da56f713cdc3174f1358a/src/webu.c#L1375) needs to remain at the very top to stop early connections. Otherwise some applications that use Motion as the back-end will not function since they attempt to connect before an image from the first pass is available.

For monitoring one wants to have the JSON status available regardless of whether a camera could be reached or not. It's crucial to be able to detect that a camera couldn't be reached for that first pass. That's the reason why I moved the passflag condition. My understanding is that the code moved before the condition doesn't touch the image. Do you concur?

> I am not sure that [this condition](https://github.com/Motion-Project/motion/blob/3c6d194d750cbeed471da56f713cdc3174f1358a/src/webu_status.c#L91) would work when there is not any camera threads and instead there is just the single motion.conf file.

It returns an empty list when called via a dedicated camera port, but the `/cameras.json` is only documented for what's called "port0" in the documentation. Anyway, I updated the code now to behave analogous to `/status.json` via the newly added `webu_status_write_list` function.

> I had been trying to avoid macros such as [this](https://github.com/Motion-Project/motion/blob/3c6d194d750cbeed471da56f713cdc3174f1358a/src/webu_status.c#L152) I would think that a function could be used instead and then just passing in the applicable args.

Converted the macro to a loop over a data structure.

**Comment by hansmi** [comment]
@Mr-Dave, could you please do another review round?

**Comment by Naphier** [comment]
Would be really nice to have this in. Automation is a bit painful when we have to parse html dom...

**Pull request merged**
