### PR TITLE
Validate text_scale

### PR DESCRIPTION
**Pull request by Mr-DaveDev**
Validate text_scale values.

### CODE REVIEW

**Comment by genius3000** [comment]
I'm sure you've tested this, but I'll try to give it a test within the next few days also.

**Comment by genius3000** [comment]
This handles the scaling check much better. Only thing I noticed (not personally concerned with but others may) is that with a 640x480 feed and scaling higher than 2, the "unable to ..." message gets dropped to a scale of 1, tougher to read on small screens. A scale of 2 doesn't change and (testing) a forced scale of 3 still fits. I understand though that while this message may be okay to take up lots of the image, the other text shouldn't.

**Comment by Mr-Dave** [comment]
I pushed another commit to permit slightly higher scaling.

**Comment by genius3000** [comment]
Gave it a quick test, the message scales up to 3 and anything beyond that gets dropped back to a 3. Didn't test thoroughly with different sized images or anything, but it looks to be working good.

**Pull request merged**
