### PR TITLE
Add the GPL v2 COPYING file.

### LINKED ISSUE #1410: little Makefile.am issue
Makefile.am references doc/COPYING which is non-existent.

As of git master commit c4822aee59420f0391f

### PR DESCRIPTION
**Pull request by tfoote**
Fixes #1410

This is the standard text for GPL content from:
http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

The convention of including the text in this file is codified at: http://www.gnu.org/licenses/gpl-howto.html

More explaination can be found here: https://stackoverflow.com/questions/5678462/should-i-provide-a-license-txt-or-copying-txt-file-in-my-project

I chose GPL v2 because it's the one cited in the neighboring copyright file:

https://github.com/Motion-Project/motion/blob/1c4822aee59420f0391f597c3b22af0a15aa0e74/doc/copyright#L1-L24

### CODE REVIEW

**Comment by Mr-Dave** [comment]
@marzal could you comment?  Your PR #1300 put the LICENSE file in the root.  The source will only have one of these.

**Comment by Marzal** [comment]
LICENSE file in the root is the standard for Gitlab/Github services to know and index licenses, so it's shown in the project and is searchable in Github. I think both ways are compatible, but if you can only use one, this PR seems to fix an issue, and mine is only an accessory improvement for Github.

I would consider using [REUSE](https://reuse.software/) if there are different files with different licenses. I'm not familiar with debian license/packaging sorry

**Comment by tfoote** [comment]
The usage of LICENSE is a more modern standard. I'd bias in that direction. The toolchain is not complaining about the lack of COPYING file and I'm sure there's a clever way to install the COPYING file for the debian packages from the LICENSE file but it's definitely not clear to me. So to that end I've updated this just to remove the unused reference and fix the build.

PS @Marzal  REUSE looks super useful. Thanks for the pointer!

**Comment by Marzal** [comment]
> PS @Marzal REUSE looks super useful. Thanks for the pointer!

Yeah, I've used REUSE in a few small projects and IMHO this could be a great standard/framework to make all projects fully documented/licensed in a way usable by machines/code.

They have a cli tool to test if the project is complaint with the framework and they also do consulting on projects if there is any difficulty.

**Comment by Mr-Dave** [comment]
Thanks.

**Pull request merged**
