### PR TITLE
Detect mysql library path in configure

### PR DESCRIPTION
**Pull request by brianjmurrell**
Currently configure makes no effort to determine if the mysqlclient lib needs a -L ld argument.

Add some code to detect where libmysqlclient.[so|a] is.

### CODE REVIEW

**Comment by Mr-Dave** [comment]
Brian, as we discussed on IRC, my preference is to avoid the hard coded directories.  I have created PR #358 which uses the pkg-config for sqlite3, mysql as well as postgre sql.  It has been tested on PI, Ubuntu and Freebsd so hopefully it will also function on Centos and resolve the issue..

**Comment by brianjmurrell** [comment]
@Mr-Dave As I commented in PR #358, while I generally am in (very much in) support of avoiding hard-coded paths, that won't work for CentOS (or any other RH derived distribution including both EL and Fedora and it's derivitaves).

**Comment by brianjmurrell** [comment]
It doesn't seem to work on my Ubuntu machine here either, which does have `libmysqlclient-dev` (5.5.50-0ubuntu0.14.04.1) installed.  Granted this is a _Ubuntu 14.04.5 LTS_ machine.  But that is still LTS and lots of people would be using it.

So I'm definitely not arguing against using `pkg-config` as a preference, but it seems that until some distros catch up to using pkg-config, we might need to still fall-back to hard-coded paths.

**Comment by Mr-Dave** [comment]
@brianjmurrell I'll be addressing this by including the path searches.  Unfortunately however, I can not take this PR as is since it is making it a hard stop when mysqlclient is not found.  There are also some issues in other distros such as Debian sid, raspbian and FreeBSD that I need to research.

**Pull request closed without merging**
