### PR TITLE
Removed text_double and added text_scale config parameter.

### PR DESCRIPTION
**Pull request by jackxbritton**

### CODE REVIEW

**Comment by Mr-Dave** [comment]
First, let me share my agreement with your enthusiasm on the commit message `Scaling works!`  There are only two revisions which I think are trivial.  

1.  Can we add the `text_double` into the depreciated options [section](https://github.com/jackxbritton/motion/blob/dbd781738c7c3a0a54da34b8b1f8f9ed0b341a97/conf.c#L1699) of the conf.c file.  If we want to be nice, we can see about changing the `text_double on` into a `text_scale 2`  

2.  Similar to the other PR on the documentation, the columns on the table refer to versions of Motion so it would be `text_double` on the first three elements and `text_scale` just on the last one.

**Comment by jackxbritton** [comment]
So I added a deprecated text_double entry to `dep_config_params`, and right away we get a segfault when I run the program with `text_double on` and ctrl-c it. Advice?

**Comment by Mr-Dave** [comment]
This seems to be caused by my last commit that included the `copy_vid_ctrl` and not your code.  It will take me some time to track down what is going on.

**Comment by Mr-Dave** [comment]
I think I have a solution to the segfault.  There is a bit too much "pointer magic" going on in here for my taste and I think that we can just call the copy_vid_ctrl function directly.  I'm posting it here if you want to try it out.  Do NOT commit it to these branches however.  I don't want you to have to take the blame for it if something else comes up with it and all this gets squashed in under your name.  

`                     strcmp(dep_config_params[i].name,"power_line_frequency")) {`
`  -                    cnt = dep_config_params[i].copy(cnt, arg1, i);`
`  +                    cnt = copy_vid_ctrl(cnt, arg1, i);`
`                 } else {`

If you try this out, please post back on whether it resolves the issue on your machine or not.

**Comment by jackxbritton** [comment]
That fixed the issue. I'll wait for your changes before I continue with mine.

**Pull request merged**
