### PR TITLE
Image Ring Process

### LINKED ISSUE #1254: With picture_output on last image is written with the next incremented event ID
0. Reviewed guide and contributing documents? (Yes/No): no
1. version [x.y.z, hash, other]: https://github.com/Motion-Project/motion/commit/dc670f5da977465241171fd01dcfc6713f49d8f2
2. installed as a package or compiled from sources [deb, rpm, git, other]: package
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]:  rtsp
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Ubuntu 18.04.4 LTS

Seems that when adding event frames (as pictures with` picture_output on` and `sql_log_picture on`) to a sqlite database (didnt tried others though), last frames are created as next event (ie %v + 1, see event column) with value defined by `text_event` (ie %C) to empty...
Here is the insertion query in config:

    sql_query insert into events(camera, event, time, type, frame, filename) values('%t', '%v.%C', '%Y-%m-%d %T', '%n', %q, '%f')

image

### PR DESCRIPTION
**Pull request by Mr-DaveDev**
Closes #1254

### CODE REVIEW

**Comment by sroller** [comment]
This is still happening. I'm at event 180 now and files from 7 event were created in the wrong path.
my parameters

    text_event %Y%m%d%H%M%S
    picture_filename %C/%v-%Y%m%d%H%M%S-%q

occasionally one or more files are written with an empty %C. Sometimes it's only one, can be up to three in my case.

**Comment by tosiara** [comment]
That original issue was about event ID incrementing before processing the last picture file. But yours, if I understand correctly, is related to `occasionally one or more files are written with an empty %C`. I think it would be better if you could create a separate issue and try to reproduce the issue with the verbose logging `-d 9`

**Comment by sroller** [comment]
Sounds good, will do.

**Comment by sroller** [comment]
As it turned out I was still running version 4.3.1 on that particular Pi. After upgrading to 4.4.0 I cannot reproduce it anymore! You might have fixed *that* issue as well when you did this one. Thank your for your response.
Have a great holiday season and stay safe in the pandemic.

**Pull request merged**
