### PR TITLE
Produce more helpful error if pkg-config not installed

### PR DESCRIPTION
**Pull request by jogu**
Currently if users run autoreconf then configure without having
pkg-config installed, they see:

./configure: line 5283: syntax error near unexpected token FFMPEG,'
./configure: line 5283:    PKG_CHECK_MODULES(FFMPEG, libavutil
libavformat libavcodec libswscale, HAVE_FFMPEG=yes)'

This is not hugely helpful and causes support queries and confusion.
It is because the pkg.m4 file that defines PKG_CHECK_MODULES is not
available of pkg-config is not installed.

To work around this, remove PKG_CHECK_MODULES and do roughly the
equivalent calling pkg-config directly. To mirror the current
behaviour, we also add a test for pkg-config being present and abort
if it is not. (I am not 100% sure this is the desired behaviour, but
regardless this commit is still an improvement on what we currently
have.)

### CODE REVIEW

**Comment by Mr-Dave** [comment]
We will need to work on this a bit more.  It looks good for stopping the configure when the pkgconf isn't installed but should we change the message to <code>the package pkgconf</code> is missing instead of <code>the program pkg-conf</code> is missing? This may assist users in finding the right thing to install.  Next, the functionality needs a bit of revision.  We need the configure to stop when ffmpeg is not detected.  Only allow the building of motion without ffmpeg  when the user actively uses the  --without-ffmpeg option.

**Comment by jogu** [comment]
> It looks good for stopping the configure when the pkgconf isn't installed but should we change the message to the package pkgconf is missing instead of the program pkg-conf is missing? This may assist users in finding the right thing to install. 

I've updated the error message to:

`required package 'pkg-config' not found, please check motion_guide.html and install necessary dependencies.`

Does that seem okay?

> Next, the functionality needs a bit of revision. We need the configure to stop when ffmpeg is not detected. Only allow the building of motion without ffmpeg when the user actively uses the --without-ffmpeg option.

Is that a regression I've caused or an existing bug in the same bit of code? I'd probably suggest fixing  it separately if the latter.

**Comment by tosiara** [comment]
No, this is not a regression. Currently by default motion will configure itself to run without ffmpeg if not available. Such build will only be able to generate jpeg files. I have a feeling, that nowadays nobody uses motion just for jpeg creation without movies and timelapse. So if you missed ffmpeg libs you will need to check configure log to see why it has configured without ffmpeg and fix and try configure again and again. Instead of that we need just to stop configure and output an error like: `FFMPEG libs not found, this is fatal error. If you want to build without ffmpeg use --without-ffmpeg param`

**Comment by jogu** [comment]
Thanks tosiara! I understand.

I'd say we should go ahead with this pull request then (assuming MrDave is happy with my new wording of the error message) and look at this ffmpeg issue separately.

**Comment by jogu** [comment]
[last push I did was just to rebase this commit onto latest master, to make a cleaner looking history when it's merged]

**Comment by jogu** [comment]
Oh, actually, this one is targeting unstable... I should open a new one going to master, right?

**Pull request closed without merging**
