### PR TITLE
h264 codec: set crf option based on configured vbr

### PR DESCRIPTION
**Pull request by ccrisan**
I wanted to be able to configure the movie quality when using the h264 codec. This sets the "crf" option according to the ffmpeg_variable_bitrate option.

### CODE REVIEW

**Comment by jogu** [comment]
@ccrisan  I may be missing something, but do you not also need a call to av_dict_set(&opts, "crf", ... ) that you pass your new crf string to?

**Comment by ccrisan** [comment]
You're damn right that line should be there. I accidentally removed it with the last commit. Thanks for notifying me.

**Comment by jogu** [comment]
The new version looks okay to me now (albeit I don't know this area of the code).

**Comment by Mr-Dave** [comment]
I would like to find a different way to accomplish this so that we can directly point the users over to the ffmpeg documentation of what the number means.  If we start converting some numbers via division then we'll end up spending all our time translating.

**Comment by ccrisan** [comment]
If the translation is not done by motion (i.e. we don't normalize the range), it will need to be done in various frontends. So far, there seem to be only two cases:

1. `ffmpeg_video_codec` set to `mp4` or `hevc` (currently of a constant, best quality), and
2. `ffmpeg_video_codec` set to anything else (as inherited from 3.2.x, I suppose).

... which leads me to believe that things are almost normalized.

In the end, users expect something close to a percentage, something that, when set to say 50% results into a video that has a perceived quality somewhere around the middle of "the worst" and "the best". At least that's what I'm struggling to provide in motionEye.

**Comment by Mr-Dave** [comment]
I agree that we need to simplify these input parms for the ffmpeg and have a simple "Quality" parameter.  I'm still struggling with the <code>* 51.0 / 32766)</code> part of this pull.  As a interim, what if we just use the exact number 1-51 directly as specified in the configuration without the division.  The VBR parm would only be checked for being outside of the acceptable range and then assigned as the CRF.  This allows for some user specification of the quality and maintain some consistency with the 1-31 values that are applicable for the other codec.

**Comment by ccrisan** [comment]
Actually, as I said before, the 1-31 range is not true. Even with 3.12.x, if you use values from 1 to 31, the quality will be the same. After some RTFS, I found out the effective range appears to be from 1 to 32767.

The formula above that I have proposed scales the [1, 32767] range to [0, 51]. Again, the reason why I went with the [1, 32767] scale is that *all* available motion codecs (in 3.12.x) appeared to be using this scale, going the same way through ffmpeg (and its quality parameter).

If you prefer that we avoid any transformation on the `ffmpeg_variable_bitrate` parameter and pass it directly to the codec, I'm fine. However the docs should then be updated to help the user choose a value. The current description (0, 2 to 31) is *wrong* in any case.

**Comment by Mr-Dave** [comment]
@ccrisan Have you observed any issues with the revisions that is on the branch under ffmpeg-fixes?  I tried to implement your suggestion of having a basic quality parameter from 1-100.  I'd like to get the issues resolved before a pull request into the project.

**Comment by ccrisan** [comment]
I haven't had the chance to test it yet but I'll make sure to run some tests this weekend and get back with a feedback.

**Comment by ccrisan** [comment]
@Mr-Dave the ffmpeg-fixes branch is it supposed to be compiled against ffmpeg 2.8, 3.0 or 3.1? Currently with 3.1 I get movies with wrong framerate (some outrageously high number).

**Comment by Mr-DaveDev** [comment]
For this purpose, it does not matter so whichever one you have installed.  Older versions would be fine as well.  

The frame rate is not wrong.  That is fixing #132 where Motion will now allow recording up to the limit specified or however fast the CPU can process the images.  The new codec/container options handle frame rates above 100 better than others.  

I did find something with the vbr/quality for the ogg type so that was included in the push I just did with the PTS changes.

**Comment by ccrisan** [comment]
Well I have set the framerate to 10 but the resulted movie is unwatchable - the framerate reported by `smplayer` is 10240! The entire movie is played within a second or so. `ffprobe` says:

```
ffprobe version 3.1.2 Copyright (c) 2007-2016 the FFmpeg developers
  built with gcc 6.1.1 (GCC) 20160802
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-netcdf --enable-shared --enable-version3 --enable-x11grab
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 41.100 / 57. 41.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 47.100 /  6. 47.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '13-51-10.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.41.100
  Duration: 00:00:00.11, start: 0.000000, bitrate: 60629 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 320x240, 60667 kb/s, 920.14 fps, 10240 tbr, 10240 tbn, 20 tbc (default)
    Metadata:
      handler_name    : VideoHandler

```

The motion daemon says:

```
[1] [NTC] [EVT] event_new_video FPS 10
[1] [NTC] [ENC] ffmpeg_open Selected Output FPS 10
[1] [NTC] [EVT] event_newfile: File of type 8 saved to: /media/data/projects/motioneye/run/Camera1/2016-08-28/13-42-40.mp4
[1] [NTC] [ALL] motion_detected: Motion detected - starting event 1
[1] [NTC] [ALL] motion_loop: End of event 1

```

My thread file looks as simple as:

```
videodevice /dev/video0
width 320
height 240
framerate 10

target_dir /media/data/projects/motioneye/run/Camera1
movie_filename %Y-%m-%d/%H-%M-%S
output_pictures off
ffmpeg_output_movies on
ffmpeg_variable_bitrate 50
ffmpeg_video_codec msmpeg4

emulate_motion on
max_movie_time 10

```

Everything seems to be fine when using the "old" codecs. I'm trying this on Arch Linux. Is there any further information you'd like me to supply to find the cause of the issue? Would you like me to open a  separate issue on this matter?

**Comment by ccrisan** [comment]
However the `ffmpeg_variable_bitrate` has no visible effect on h264 movies and with msmpeg4 codec it crashes with:


```
[1] [NTC] [ENC] ffmpeg_open Selected Output FPS 10
[1] [NTC] [ENC] ffmpeg_avcodec_log: Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[1] [NTC] [EVT] event_newfile: File of type 8 saved to: /media/data/projects/motioneye/run/Camera1/2016-08-28/14-25-58.avi
[1] [NTC] [ALL] motion_detected: Motion detected - starting event 1
[1] [NTC] [ENC] ffmpeg_avcodec_log: Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly

[1] [ERR] [ENC] ffmpeg_avcodec_log: Application provided invalid, non monotonically increasing dts to muxer in stream 0: 1 >= 1

[1] [ERR] [ENC] ffmpeg_put_frame: Error while writing video frame: No such file or directory

```

**Comment by Mr-DaveDev** [comment]
We don't need another issue.  I missed the msmpeg4.  Thanks.  I was seeing the ffmpeg_variable_bitrate work so I will test that again.  If you are curious, the log level of INF does now report vbr/crf being used.

**Pull request merged**
