### PR TITLE
Add missing "static" qualifiers on functions

### PR DESCRIPTION
**Pull request by jogu**
Trivial fixes for a few warnings when building with --with-developer-flags.

### CODE REVIEW

**Comment by tosiara** [comment]
What were the warnings?

**Comment by jogu** [comment]
The usual gcc missing prototypes warning:

> -Wmissing-prototypes (C and Objective-C only)
> Warn if a global function is defined without a previous prototype declaration. This warning is issued even if the definition itself provides a prototype. Use this option to detect global functions that do not have a matching prototype declaration in a header file.

**Comment by tosiara** [comment]
Can you please paste how those warnings look like and which compiler/system are you using?
I don't get any warnings about static qualifiers

**Comment by jogu** [comment]
debian wheezy, gcc 4.9.2, running configure with --with-developer-flags



netcam_rtsp.c:34:5: warning: no previous prototype for ‘netcam_check_pixfmt’ [-Wmissing-prototypes]
 int netcam_check_pixfmt(netcam_context_ptr netcam){
     ^
netcam_rtsp.c:50:6: warning: no previous prototype for ‘netcam_rtsp_null_context’ [-Wmissing-prototypes]
 void netcam_rtsp_null_context(netcam_context_ptr netcam){
      ^
netcam_rtsp.c:65:6: warning: no previous prototype for ‘netcam_rtsp_close_context’ [-Wmissing-prototypes]
 void netcam_rtsp_close_context(netcam_context_ptr netcam){
      ^
netcam_rtsp.c:375:5: warning: no previous prototype for ‘netcam_rtsp_resize_ntc’ [-Wmissing-prototypes]
 int netcam_rtsp_resize_ntc(netcam_context_ptr netcam){


Regardless of warnings or not, these functions should be static. They are not called from other modules nor (given, e.g., the netcam_rtsp ones are exposed via function pointers in it's structures iirc and that none of them are present in any .h files) are they intended to be directly called.

**Comment by tosiara** [comment]
Hmmmm... I'm on openSUSE 13.1 with gcc version 4.8.3 20140627. All I get is some warnings about deprecated ffmpeg functions:
```
gcc -g -O2 -D_REENTRANT -DMOTION_V4L2 -DMOTION_V4L2_OLD -DTYPE_32BIT="int" -DHAVE_BSWAP -W -Wshadow -Wpointer-arith -Wcast-align -Wwrite-strings -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Winline -Wredundant-decls -Wno-long-long -ggdb -g3   -march=native -mtune=native -Wall -DVERSION=\"3.4.1+gite44a5a9\" -Dsysconfdir=\"/usr/local/etc\" -I/root/ffmpeg/out/include    -c -o netcam_rtsp.o netcam_rtsp.c
netcam_rtsp.c: In function Б─≤decode_packetБ─≥:
netcam_rtsp.c:138:5: warning: Б─≤avcodec_decode_video2Б─≥ is deprecated (declared at /root/ffmpeg/out/include/libavcodec/avcodec.h:4784) [-Wdeprecated-declarations]
     retcd = avcodec_decode_video2(cc, frame, &check, packet);
     ^
netcam_rtsp.c: In function Б─≤netcam_open_codecБ─≥:
netcam_rtsp.c:196:5: warning: Б─≤codecБ─≥ is deprecated (declared at /root/ffmpeg/out/include/libavformat/avformat.h:882) [-Wdeprecated-declarations]
     dec_ctx = st->codec;
     ^
netcam_rtsp.c: In function Б─≤netcam_rtsp_open_contextБ─≥:
netcam_rtsp.c:497:5: warning: Б─≤codecБ─≥ is deprecated (declared at /root/ffmpeg/out/include/libavformat/avformat.h:882) [-Wdeprecated-declarations]
     netcam->rtsp->codec_context = netcam->rtsp->format_context->streams[netcam->rtsp->video_stream_index]->codec;
     ^
```

**Comment by jogu** [comment]
Weird. You *should* get the errors. I'm going to accuse your version of gcc of being buggy in this area I think :)

**Comment by Mr-Dave** [comment]
I have been working on the ffmpeg and would prefer to just pull in this same fix from my ffmpeg-fixes branch.

**Comment by jogu** [comment]
Sounds good to me :)

**Pull request closed without merging**
