### PR TITLE
Changed MOTION_LOG macro

### PR DESCRIPTION
**Pull request by tosiara**
Changed MOTION_LOG macro and removed "%s:" from the format string
Function name will be now auto added

### CODE REVIEW

**Comment by tosiara** [comment]
We should decide asap either this pull is useful or not. Since this updates every existing call to logging - any further pull request will most probably cause conflicts. So its going to be a pain for me to constantly resolve those conflicts and keep this PR up to date
If community is not interested in this enhancement I will rather close it

**Comment by genius3000** [comment]
I'd like to see this merged, it may seem trivial but it does remove a common point of confusion. I definitely spent a bit of time wondering what that '%s' was there for.

**Comment by genius3000** [comment]
All the changes look straight forward and proper to me, except for:
- ffmpeg.c needs updating again from the rebase and conflicts.
- maybe squash that rebase commit, so it's not polluting the history with a double change.

**Comment by tosiara** [comment]
Please elaborate why ffmpeg.c needs an update? I see no conflicts at the moment (after I pushed https://github.com/Motion-Project/motion/pull/428/commits/47fa1b1876790ba3baf9831d3699a8b9879ff354)

**Comment by genius3000** [comment]
I'm still seeing `%s: ` on the four changed log lines.

**Comment by tosiara** [comment]
Ah, you are right incomplete resolution. This needs to be rebased. Will do now

**Comment by genius3000** [comment]
Looks like ffmpeg.c:706 and ffmpeg.c:946 still have the old format too.

**Comment by tosiara** [comment]
Updated!
Thanks, I appreciate your help

**Pull request merged**
