### PR TITLE
Add webp image compression support

### PR DESCRIPTION
**Pull request by jayslovak**

### CODE REVIEW

**Comment by tosiara** [comment]
Question. Does webp support live stream like MJPEG? I mean, can we use it as option for motion's stream?

**Comment by jayslovak** [comment]
I am not aware of webp supporting streaming like mjpeg. My plan is to implement VP8 video codec for the web stream once this is done (part of my bandwidth optimization efforts).
But I might give streaming webp a shot, it wasn't a planned feature for jpeg anyways...

**Comment by jayslovak** [comment]
BTW the build is passing now, I forgot to add the jenkins updates in the first commit.

**Comment by tosiara** [comment]
VP8 for streaming sounds promising too. I'm also interested to measure not only bandwidth, but also how much cpu resources it takes on ARM devices compared to MJPEG

**Comment by jayslovak** [comment]
I have tested doing VP8 compression using V4L2 video pipe on my old raspberry pi and it was working quite well. Much better than re-compressing the mjpeg stream from motion HTTP server.

**Comment by Mr-DaveDev** [comment]
I have a few small requests that are probably easier for you to push into the branch rather than me trying to add.  

- Can we change the configure to use --without-webp instead of --without-libwebp
- Can we use the <code>AC_DEFINE([HAVE_WEBP], 1, [Define to 1 if WEBP is around])</code>
rather than the CFLAGS (I've been trying to replace all the ones we currently have)
- In the build section of the guide, it lists the required packages as 
  <code>sudo apt-get install autoconf automake build-essential pkgconf libtool git libzip-dev libjpeg62 libjpeg62-dev libwebp5 libwebpmux1</code> 
instead of 
<code>sudo apt-get install autoconf automake build-essential pkgconf libtool git libzip-dev libjpeg62 libjpeg62-dev libwebp-dev</code> 
- We will need to figure out the processing when it is built using --without-libwebp and then the user selects webp as the output option.  Currently it puts out zero byte files.  Can we see about throwing an error at the user and having it fall back to being JPG?

**Comment by jayslovak** [comment]
Sure, I hope this will be acceptable.

**Pull request merged**
