### PR TITLE
Fix for file names that contain "/" and non existing subdirs

### PR DESCRIPTION
**Pull request by tosiara**
See https://github.com/Motion-Project/motion/issues/360#issuecomment-320937660
This is a fix to unblock users who wants to use latest version
Further discussion is needed to make a standard for file names

### CODE REVIEW

**Comment by jasaw** [comment]
I've just tested this, works for me.
Thanks for the fix.

**Comment by jasaw** [comment]
I noticed the whitespaces in front of the added lines are tabs when the rest of the file uses space. You might want to change the tabs to spaces for consistency.

**Comment by tosiara** [comment]
Yes, sorry. Used another machine with vim configured to use tabs
Thanks for verifying

**Comment by tosiara** [comment]
I think this can be called a valid permanent fix. Because if we allow using "/" in file names (that's how motion behaved all the time), we do need to create path all the time for every call. So I will change the title of the PR to say this is a permanent fix

**Pull request merged**
